"""empty message

Revision ID: b6491cf5f005
Revises: 91721ff0882a
Create Date: 2024-05-31 10:09:01.689046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6491cf5f005'
down_revision = '91721ff0882a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date_publication', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('date_publication')
        batch_op.drop_column('body')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
