"""empty message

Revision ID: c55d05a8bfc2
Revises: b6491cf5f005
Create Date: 2024-05-31 11:22:39.017645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55d05a8bfc2'
down_revision = 'b6491cf5f005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('image_url')
        batch_op.drop_column('date_publication')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date_publication', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
